### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by windbender** [brechtbilliet/angular-typescript-webpack#11]
For those of us who might be using your wonderful template for our own projects, it would be very useful for you to have a license file so we know how we might be able to do so.

My personal vote would be for an Apache or MIT, but it's your code.

https://help.github.com/articles/open-source-licensing/

**Comment by brechtbilliet** [comment]
Good point man. I forgot that, enjoy the MIT License!

**Comment by windbender** [comment]
wow.  that was almost time-travel-esqe fast.   Thanks.
