### ISSUE TITLE
Debugging specs

### ISSUE THREAD

**Issue by gpicazo** [brechtbilliet/angular-typescript-webpack#12]
Hi, awesome boilerplate. I actually have a project that has a very similar structure. One of the things that I haven't quite figured out is how to properly debug specs using phantomjs as the browser. With a traditional UI browser, I can actually put breakpoints during the execution of the tests, but am unsure how to do it with phantomJS. Any advice?

**Comment by brechtbilliet** [comment]
Your Ide could be able to :)
Op 2 apr. 2016 19:11 schreef "gpicazo" <notifications@github.com>:
>
> Hi, awesome boilerplate. I actually have a project that has a very
similar structure. One of the things that I haven't quite figured out is
how to properly debug specs using phantomjs as the browser. With a
traditional UI browser, I can actually put breakpoints during the execution
of the tests, but am unsure how to do it with phantomJS. Any advice?

**Comment by blowsie** [comment]
@brechtbilliet Out of curiosity, Which IDE are you using?

I'm trying to figure out how I can have WebStorm do the following simultaneously

- wallaby tests
- npm start
- Breakpoints in Typescript inside WebStorm

Having these three things run together inside the IDE would be great.

**Comment by blowsie** [comment]
> - Breakpoints in Typescript inside WebStorm

Looks like this may not be possible with webpack, since webpack creates a virtual directory.

![image](https://cloud.githubusercontent.com/assets/308572/14735944/df86e60c-086b-11e6-9283-9aa43cb54086.png)

**Comment by brechtbilliet** [comment]
I use webstorm @blowsie 
I allways debug in the browser (chrome dev tools). In theory webstorm should be able to do that too with the use of sourcemaps, but I haven't tried that yet.
Wallaby.js runs fine in webstorm. Just reference the wallaby.js file as configuration file

**Comment by blowsie** [comment]
Update, I was able to use webstorm debugging with some guidance from this article.
https://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/

Now I can simply switch between debugging in chrome and webstorm by simply closing / opening chrome dev tools :+1:

**Comment by brechtbilliet** [comment]
Nice! Thanks for the update!
