### ISSUE TITLE
Weaving Angular config and classes

### ISSUE THREAD

**Issue by cveld** [brechtbilliet/angular-typescript-webpack#13]
What is your guidance about weaving Angular configuration such as registering controllers, services, etc. with the Angular module system and defining classes?
As importing classes and typings should not have side-effects, cf. https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit
I am trying to set up a practice of bundling the loading of Angular configuration in a couple of hierarchical ordered TypeScript files that are imported by the syntax:

```import "modulename";```

which will enforce the execution of the static code within it. In some cases this requires me to setup double .ts-files:
* ```mycode.ts```; imported by ```import {myclass1, mytype1} from "./mycode";```
* ```mycode.angular.ts```; imported by ```import "mycode.angular.ts";```

This does not look like the best solution. What is your guidance?

**Comment by brechtbilliet** [comment]
I"m not sure what you mean with your question.
If you mean register controllers and services with angular, I always do it in an index.ts file for every angular module, like so
`import {SharedModel} from "../core/models/impl/SharedModel";
import {SidebarModel} from "../core/models/impl/SidebarModel";
import {TopbarModel} from "../core/models/impl/TopbarModel";
import {TweetService} from "../core/services/impl/TweetService";

angular.module("app.tweets", ["ngRoute"])
    .service("ContentModel", ContentModel)
    .service("SharedModel", SharedModel)
    .service("SidebarModel", SidebarModel)`

If you want to export angular modules you can do it like so:

`export var tweetMod: IModule = angular.module('app.tweets')....`

and use it like this:
`import {tweetMod} from './tweets/index';
angular.module('app', [tweetMod.name]);
`
Does that answer your question?

**Comment by brechtbilliet** [comment]
Since no further comments, I'm going to close this issue.
