### ISSUE TITLE
2 step compilation

### ISSUE THREAD

**Issue by nikolaymatrosov** [brechtbilliet/angular-typescript-webpack#7]
What is the purpose of transpling Typescript to ES6 via tsc, and then ES6 to ES5 via Babel? Why you can't use only tsc targeting ES5?

**Comment by brechtbilliet** [comment]
It's a personal choice I guess. I like it when my IDE compiles to es6 because it's more readable.
But I understand what you mean.

**Comment by nikolaymatrosov** [comment]
Thanks for explaining. At first I thought there are some hidden pitfals of direct compilation, that you have encountered.
