### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by Mishurin** [brechtbilliet/angular-typescript-webpack#8]
Hi! Ho do you actually run your tests? Seems like they are out of configuration? I noticed also there are some updates needed to run build, for example ts-loader.

**Comment by brechtbilliet** [comment]
Hi Igor,

I run them with wallaby.js for the moment.
Indeed there are some problems with the package.json, I’ll fix them asap

**Comment by Mishurin** [comment]
Hi, Brecht! I haven't noticed that from the start :) Thank you! I reead about wallaby. It looks like jsTestDriver for Intelli IDEA. In fact, it was not easy to understand what actually happens beetween karma web pack and all those dependecnies :)  By the way, I also met some problems building phantomjs on Windows. This is a really annoying thing that requires C++ compiler and python and other stuff.

**Comment by brechtbilliet** [comment]
Fixed
